version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: error-return
      - name: error-strings
      - name: unexported-return
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
